package config

var ExtensionMap = map[string]string{
	".pdf":  "Documents",
	".docx": "Documents",
	".doc":  "Documents",
	".txt":  "Documents",
	".webp": "Images",
	".heic": "Images",
	".gif":  "Images",
	".svg":  "Images",
	".png":  "Images",
	".jpg":  "Images",
	".jpeg": "Images",
	".gz":   "Archives",
	".zip":  "Archives",
	".rar":  "Archives",
	".jar":  "Archives",
	".csv":  "Spreadsheets",
	".xlsx": "Spreadsheets",
	".xls":  "Spreadsheets",
	".mp4":  "Media",
	".mp3":  "Media",
	".mov":  "Media",
	".webm": "Media",
	".exe":  "Installers",
	".pkg":  "Installers",
	".dmg":  "Installers",
	".html": "Code",
	".css":  "Code",
	".xml":  "Code",
	".js":   "Code",
	".json": "Code",
	".py":   "Code",
}
